
source $HOME/.vim/vimrc_plugin_definitions
source $HOME/.vim/vimrc_settings
source $HOME/.vim/vimrc_commands
source $HOME/.vim/vimrc_mappings
source $HOME/.vim/vimrc_autocmds

if &loadplugins
  source $HOME/.vim/vimrc_plugin_settings
endif

let g:session_autosave = 'yes'
let g:session_autoload = 'yes'
