if [ -f ~/dotfiles/zsh/zsh_path ] ; then
  . ~/dotfiles/zsh/zsh_path
fi

if [ -f ~/dotfiles/zsh/zsh_aliases ] ; then
  . ~/dotfiles/zsh/zsh_aliases
fi

if [ -f ~/dotfiles/zsh/zsh_settings ] ; then
  . ~/dotfiles/zsh/zsh_settings
fi

if [ -f ~/dotfiles/zsh/zsh_functions ] ; then
  . ~/dotfiles/zsh/zsh_functions
fi

if [ -f ~/dotfiles/zsh/zsh_android ] ; then
  . ~/dotfiles/zsh/zsh_android
fi

if [ -f ~/dotfiles/zsh/zsh_auth ] ; then
  . ~/dotfiles/zsh/zsh_auth
fi

if [ -f ~/dotfiles/zsh/zsh_local ] ; then
  . ~/dotfiles/zsh/zsh_local
fi

if [ -f ~/dotfiles/zsh/zsh_autorun ] ; then
  . ~/dotfiles/zsh/zsh_autorun
fi

if [ -f ~/dotfiles/zsh/zsh_travis ] ; then
  . ~/dotfiles/zsh/zsh_travis
fi

if [ -f ~/.nvm/nvm.sh ] ; then
  . ~/.nvm/nvm.sh
fi

if [ -f /usr/local/opt/asdf/asdf.sh ] ; then
  . /usr/local/opt/asdf/asdf.sh
fi
