# ~/.bash_profile: executed by bash for login shells.

if [ -e ~/.bashrc ] ; then
  . ~/.bashrc
fi

if [ -e ~/dotfiles/bash/bashrc ] ; then
  . ~/dotfiles/bash/bashrc
fi

# Put all local machine customizations in ~/.bash_local
if [ -e ~/.bash_local ] ; then
  . ~/.bash_local
fi

# Put all local machine customizations in ~/.bash_local
if [ -e ~/dotfiles/bash/bash_local ] ; then
  . ~/dotfiles/bash/bash_local
fi

if [ -e ~/.bash_aliases ] ; then
  . ~/.bash_aliases
fi

if [ -e ~/dotfiles/bash/bash_aliases ] ; then
  . ~/dotfiles/bash/bash_aliases
fi

export JAVA_HOME=`/usr/libexec/java_home -v 1.7`
export JAVA6_HOME=`/usr/libexec/java_home -v 1.6`
export JAVA7_HOME=`/usr/libexec/java_home -v 1.7`
export JAVA8_HOME=`/usr/libexec/java_home -v 1.8`

if [ -x /usr/libexec/path_helper ]; then
  eval $(/usr/libexec/path_helper -s)
fi
